### PR TITLE
Gfunction generator CPU version

### PR DESCRIPTION
**Pull request by yazhai**
CPU version of G-function generator is finished.

Compatible with `fopenmp`, and requires "CBLAS" library support, such as GSL `lgslcblas`

### CODE REVIEW

**Comment by yazhai** [comment]
@zonca @agoetz @ThuongTNguyen 
The CPU code of G-function generator is ready for review.
Please send me your feedback and comments.

Thanks a lot!

**Comment by zonca** [comment]
I'm not very familiar with this, @agoetz can you review it?

**Comment by agoetz** [comment]
@zonca @yazhai I will review asap.

**Comment by yazhai** [comment]
Hello all @zonca @agoetz @ndanandeh 

Now all functions are templaterized, compatible with single/double precision.

Normalization of results are finished. Ready to put directly into NN codes.

`cblas`, `fopenmp`, compiler type and optimization flags are possible to switch on/off at compiling time.

TODO: add mkl_cblas support.

Yaoguang

Edit: MKL_CBLAS support is added on Oct 25th, 2017

**Pull request closed without merging**
